### ISSUE TITLE
`using` and null result

### ISSUE THREAD

**Issue by bclothier** [DotNetAnalyzers/IDisposableAnalyzers#128] opened 2018-11-05 01:38 UTC
Blindly adopting the recommendation from the IDisposable analyzer for [this code](https://github.com/rubberduck-vba/Rubberduck/pull/4491/files/9bfbca0c70aeb0bc928930cf931d3713b13abb59#diff-517ac0389bbb5ec58c121c460a951084) --

Originally:
```
            var classGuidKey = Registry.LocalMachine.OpenSubKey(@"SYSTEM\CurrentControlSet\Control\Class\" + classGuid);
```

After recommendation:
```
            using (var classGuidKey =
                Registry.LocalMachine.OpenSubKey(@"SYSTEM\CurrentControlSet\Control\Class\" + classGuid))
```

What I failed to consider at the time was that the `OpenSubKey` could return a `null`. Therefore wrapping it in a `using` directly is actually not safe. 

I'm not sure if it's possible to determine this possibility but in case it is, it might be good to have analyzers be aware of methods that may return `null`s. Even if we can't analyze the framework's code, our implementation definitely could be analyzed to ensure that it should not return a `null` and thus throw when entering the `using` block.

**Comment by sharwell** [comment] 2018-11-05 03:32
The specification for [using statements](https://github.com/dotnet/csharplang/blob/master/spec/statements.md#the-using-statement) explicitly shows that `null` will not throw when used as a resource.

**Comment by JohanLarsson** [comment] 2018-11-05 07:50
Closing this as by design. Don't let it discourage you, keep the issues coming!

**Closed by JohanLarsson** 2018-11-05 07:50 UTC
