### ISSUE TITLE
IDISP003. Invalid diagnostic of re-assigning

### ISSUE THREAD

**Issue by kuzyaka** [DotNetAnalyzers/IDisposableAnalyzers#107] opened 2018-08-24 15:04 UTC
public class Demo
{
	private MemoryStream ms;

	public MemoryStream ResponseStream
	{
		get => ms ?? (ms = new MemoryStream()); // invalid IDISP003; ms is null on the right of "??" operator
		set => ms = value;
	}
}

**Comment by JohanLarsson** [comment] 2018-10-15 10:34
Er, analyzer does the right thing here it is by design.

If you have:
```cs
public MemoryStream ResponseStream
{
	get => this.responseStream ?? (this.responseStream = new MemoryStream());
}
```

It is valid and the analyzer does not nag.
Having a public setter creates an impossible situation because:

1. In the lazy getter the field can be assigned with a `MemoryStream` created by us that we are responsible for disposing.
2. The public setter means it can be assigned with streams that we don't own and should not dispose.

The diagnostics are probably not very accurate here but at least they are drawing attention to the problematic design.

Closing this as by design.

**Comment by JohanLarsson** [comment] 2018-10-15 10:35
There is a race condition in the setter so even the IDISP003 is not completely wrong there.

**Closed by JohanLarsson** 2018-10-15 10:35 UTC

**Comment by JohanLarsson** [comment] 2018-10-15 10:45
Maybe you can use something like:
```cs
public sealed class Demo : IDisposable
{
    private MemoryStream empty;
    private MemoryStream responseStream;
    private bool disposed;

    public MemoryStream ResponseStream
    {
        get => this.responseStream ?? this.empty ?? (this.empty = new MemoryStream());
        set => this.responseStream = value;
    }

    public void Dispose()
    {
        if (this.disposed)
        {
            return;
        }

        this.disposed = true;
        this.empty?.Dispose();
    }
}
```

It does not feel like an awesome design but at least it keeps created and injected separate.
I prefer auto property and letting it return null there.
